document.write( '<footer>\n' );
document.write( '      <div class=\"thirdFooter\" id=\"central\">\n' );
document.write( '        <h4>Central de Atendimento</h4>\n' );
document.write( '        <h5>(xx) xxxxx-xxxx</h5>\n' );
document.write( '        <h5>Meus pedidos</h5>\n' );
document.write( '        <h5>Fale conosco</h5>\n' );
document.write( '        <h5>Formas de pagamento</h5>\n' );
document.write( '        </div>\n' );
document.write( '      <div class=\"firstFooter\">\n' );
document.write( '        <h4>Institucional</h4>\n' );
document.write( '        <h5>Quem somos</h5>\n' );
document.write( '        <h5>Trabalhe conosco</h5>\n' );
document.write( '        <h5>Políticas de privacidade</h5>\n' );
document.write( '        </div>   \n' );
document.write( '      <div class=\"firstFooter\">\n' );
document.write( '        <h4>Horário de funcionamento</h4>\n' );
document.write( '        <h5>Segunda à sexta-feira das 08:00 às 23:00.</h5>\n' );
document.write( '        <h5>Sábados e domingo das 08:00 às 21:00.</h5>\n' );
document.write( '        </div>   \n' );
document.write( '  </footer>' );
